kind: ConfigMap
apiVersion: v1
metadata:
  name: home-assistant-configmap
data:
  known_devices.yaml: {{ .Values.known_devices }}
  automations.yaml: {{ .Values.automations }}
  configuration.yaml: {{ .Values.configuration }}