{{- if .Values.configuration.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}-configuration
data:
  configuration.yaml: |
    {{- tpl .Values.configuration.templateConfig . | nindent 4 }}
{{- end -}}