apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "home-assistant.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: home-assistant
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- if .Values.configuration.enabled }}
        checksum/init-script: {{ include (print $.Template.BasePath "/configmap-init-script.yaml") . | sha256sum }}
        checksum/ha-configuration: {{ include (print $.Template.BasePath "/configmap-ha-config.yaml") . | sha256sum }}
        {{- end }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "home-assistant.labels" . | nindent 8 }}
        app.kubernetes.io/component: home-assistant
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "home-assistant.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.image }}
          image: "{{ coalesce $.Values.global.image.registry .registry }}/{{ .repository }}:{{ .tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ coalesce $.Values.global.image.pullPolicy .pullPolicy }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: {{ include "home-assistant.fullname" . }}-pvc
              mountPath: /config
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- if or (.Values.configuration.enabled) .Values.initContainers }}
      initContainers:
        {{- if .Values.initContainers }}
        {{- toYaml .Values.initContainers | nindent 8 }}
        {{- end }}
        {{- if .Values.configuration.enabled }}
        - name: {{ .Values.configuration.initContainer.name }}
          image: {{ .Values.configuration.initContainer.image }}
          {{- if .Values.configuration.initContainer.securityContext }}
          securityContext:
            {{- toYaml .Values.configuration.initContainer.securityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.configuration.initContainer.command }}
          command: {{ toYaml .Values.configuration.initContainer.command | nindent 12 }}
          {{- end }}
          {{- if .Values.configuration.initContainer.args }}
          args: {{ toYaml .Values.configuration.initContainer.args | nindent 12 }}
          {{- end }}
          {{- if .Values.configuration.initContainer.env }}
          env:
            {{- toYaml .Values.configuration.initContainer.env | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- range .Values.configuration.initContainer.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{ end }}
            {{- end }}
            - mountPath: /config
              name: {{ include "home-assistant.fullname" . }}-pvc
        {{- end }}
      {{- end }}
      volumes:
        {{- if .Values.configuration.enabled }}
        - name: init-volume
          configMap:
            name: {{ include "home-assistant.fullname" . }}-init-script
        - name: config-volume
          configMap:
            name: {{ include "home-assistant.fullname" . }}-configuration
        {{- end }}
        {{- if .Values.persistence.enabled }}
        - name: {{ include "home-assistant.fullname" . }}-pvc
          {{- if and .Values.persistence.hostPath (ne .Values.persistence.storageClass "manual" ) }}
          hostPath:
            path: {{ .Values.persistence.hostPath }}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "home-assistant.fullname" . }}-pvc{{- end }}
          {{- end }}
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
