apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - name: bluez
        image: ghcr.io/mysticrenji/bluez-service:v1.0.0
        securityContext:
          privileged: true
      - name: matter-server
        image: ghcr.io/home-assistant-libs/python-matter-server:stable
        securityContext:
          # Needed for Bluetooth via dbus
          allowPrivilegeEscalation: true
          capabilities:
            add:
              - SYS_ADMIN
        imagePullPolicy: Always
        args:
          - --storage-path=/data
          - --paa-root-cert-dir=/data/credentials
          - --bluetooth-adapter=0
        ports:
        - containerPort: 5580 # Expose container port
      - name: home-assistant
        image: homeassistant/home-assistant:{{ .Values.home-assistant.version }}
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
        ports:
        - containerPort: 8123
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /config/configuration.yaml
          subPath: configuration.yaml
          name: configmap-file
        - mountPath: /config/automations.yaml
          subPath: automations.yaml
          name: configmap-file
        - mountPath: /media
          name: media-volume          
        - mountPath: /run/dbus
          name: d-bus
        #   readOnly: true
        - mountPath: /dev/ttyUSB1
          name: zigbee
        - name: data-volume
          mountPath: /data
        #- mountPath: /dev/video0
        #  name: cam
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - SYS_ADMIN
      hostNetwork: true
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: home-assistant-pvc
      - name: media-volume
        hostPath:
          path: /tmp/media
      - name: configmap-file
        configMap:
          name: home-assistant-configmap
      #  hostPath:
      #    path: /tmp/home-assistant
      #    type: DirectoryOrCreate
      - name: d-bus
        hostPath:
          path: /run/dbus
      - name: data-volume
        hostPath:
          path: /tmp/media
      - name: zigbee
        hostPath:
          path: /dev/ttyACM0
      #- name: cam
      #  hostPath:
      #    path: /dev/video0