{{- if .Values.configuration.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}-init-script
  namespace: {{ .Release.Namespace }}
data:
  init.sh: |
    {{- tpl .Values.configuration.initScript . | nindent 4 }}
{{- end -}}