apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
spec:
  selector:
    app: home-assistant
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8123
  - name: ws
    protocol: TCP
    port: 5580       # Matter Server Port
    targetPort: 5580 # Matter Server container port