apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service-service
spec:
  selector:
    app: mosquitto-service
  type: NodePort
  ports:
  - name: mqtt
    protocol: TCP
    port: 1883
    targetPort: 1883
  - name: mqtt1
    protocol: TCP
    port: 9001
    targetPort: 9001 