apiVersion: v1
kind: Service
metadata:
  name: zwavejs2mqtt-service
spec:
  selector:
    app: zwavejs2mqtt
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8091
    targetPort: 8091
    nodePort: 30091
  - name: ws
    protocol: TCP
    port: 3000
    targetPort: 3000